<?php

namespace ConfigMigrationsDemo;

// DO NOT MODIFY THIS FILE!
// IT IS AUTO-GENERATED BY ROCKMIGRATIONS!

trait RockMigrationsConstants
{
  const field_bar = 'configmigrationsdemo_bar';
  const field_foo = 'configmigrationsdemo_foo';
  const template_test = 'configmigrationsdemo_test';
}
